# Generated by Django 5.1.5 on 2025-01-16 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_image_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
