# Generated by Django 5.1.5 on 2025-01-16 14:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_remove_image_dislikes_remove_image_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
